import json

semantic_model = {
    "tables": [
        {
            "table_name": "v_customers",
            "table_description": "Customer details view. Each row is one customer with all attributes as columns.",
            "columns": [
                {"name": "customer_id", "type": "INT", "description": "Unique customer ID (e.g. 1, 2, 3)"},
                {"name": "customer_name", "type": "VARCHAR", "description": "Full customer name (e.g. 'SALTPRINCETON', 'WELLSFARGO', 'CHRISGAYLE')"},
                {"name": "status", "type": "VARCHAR", "description": "Customer status (e.g. 'ACTIVE')"},
                {"name": "customer_number", "type": "VARCHAR", "description": "Customer number identifier"},
                {"name": "email", "type": "VARCHAR", "description": "Email address (e.g. 'ACME@GMAIL.COM')"},
                {"name": "phone", "type": "VARCHAR", "description": "Primary phone number"},
                {"name": "city", "type": "VARCHAR", "description": "Billing city (e.g. 'CASSSTMONTEREY', 'SANDIMAS')"},
                {"name": "state", "type": "VARCHAR", "description": "Billing state (e.g. 'CA')"},
                {"name": "zip_code", "type": "VARCHAR", "description": "Billing ZIP code"},
                {"name": "address", "type": "VARCHAR", "description": "Lookup address"},
                {"name": "tax_id", "type": "VARCHAR", "description": "Tax ID"},
                {"name": "provider_ref", "type": "VARCHAR", "description": "Provider ID (FK to v_providers.provider_id)"},
                {"name": "add_date", "type": "VARCHAR", "description": "Date customer was added"},
                {"name": "add_user", "type": "VARCHAR", "description": "User who added the customer"},
            ],
        },
        {
            "table_name": "v_policies",
            "table_description": "Policy details view. Each row is one insurance policy with all attributes as columns.",
            "columns": [
                {"name": "policy_id", "type": "INT", "description": "Unique policy ID"},
                {"name": "policy_number", "type": "VARCHAR", "description": "Policy number (e.g. 'MLP00000001')"},
                {"name": "policy_display_number", "type": "VARCHAR", "description": "Display policy number"},
                {"name": "status", "type": "VARCHAR", "description": "Policy status ('ACTIVE' or 'CANCELLED')"},
                {"name": "status_code", "type": "VARCHAR", "description": "Status code"},
                {"name": "customer_ref", "type": "VARCHAR", "description": "Customer ID (FK to v_customers.customer_id). Stored as string — use CAST(customer_ref AS UNSIGNED) for joins."},
                {"name": "provider_ref", "type": "VARCHAR", "description": "Provider ID (FK to v_providers.provider_id). Stored as string."},
                {"name": "expiration_date", "type": "VARCHAR", "description": "Expiration date in YYYYMMDD format (e.g. '20270203')"},
                {"name": "index_name", "type": "VARCHAR", "description": "Policy index name"},
                {"name": "quote_number", "type": "VARCHAR", "description": "Quote number"},
                {"name": "transaction_code", "type": "VARCHAR", "description": "Transaction code"},
                {"name": "city", "type": "VARCHAR", "description": "City"},
                {"name": "state", "type": "VARCHAR", "description": "State code"},
                {"name": "postal_code", "type": "VARCHAR", "description": "Postal code"},
                {"name": "email", "type": "VARCHAR", "description": "Contact email"},
                {"name": "contact_number", "type": "VARCHAR", "description": "Contact phone number"},
                {"name": "tax_id", "type": "VARCHAR", "description": "Tax ID"},
            ],
        },
        {
            "table_name": "v_providers",
            "table_description": "Provider/producer details view. Each row is one insurance provider, agent, or financial institution.",
            "columns": [
                {"name": "provider_id", "type": "INT", "description": "Unique provider ID"},
                {"name": "provider_name", "type": "VARCHAR", "description": "Provider name (e.g. 'AGENTBILLPRODUCERI')"},
                {"name": "provider_type", "type": "VARCHAR", "description": "Type: 'PRODUCER' or 'FINANCIAL INSTITUTION'"},
                {"name": "provider_number", "type": "VARCHAR", "description": "Provider number"},
                {"name": "business_name", "type": "VARCHAR", "description": "Business name"},
                {"name": "personal_name", "type": "VARCHAR", "description": "Personal name (if individual)"},
                {"name": "status_code", "type": "VARCHAR", "description": "Status code"},
                {"name": "city", "type": "VARCHAR", "description": "City"},
                {"name": "state", "type": "VARCHAR", "description": "State code (e.g. 'CA')"},
                {"name": "postal_code", "type": "VARCHAR", "description": "Postal code"},
                {"name": "street_address", "type": "VARCHAR", "description": "Street address"},
                {"name": "phone", "type": "VARCHAR", "description": "Phone number"},
                {"name": "tax_id", "type": "VARCHAR", "description": "Tax ID"},
                {"name": "producer_agency", "type": "VARCHAR", "description": "Producer agency"},
                {"name": "producer_group", "type": "VARCHAR", "description": "Producer group"},
            ],
        },
        {
            "table_name": "v_commissions",
            "table_description": "Commission payment records view.",
            "columns": [
                {"name": "commission_id", "type": "INT", "description": "Unique commission ID"},
                {"name": "commission_amount", "type": "DECIMAL", "description": "Commission dollar amount"},
                {"name": "premium_amount", "type": "DECIMAL", "description": "Premium amount"},
                {"name": "transaction_date", "type": "DATE", "description": "Transaction date"},
                {"name": "provider_ref", "type": "INT", "description": "FK to v_providers.provider_id"},
                {"name": "policy_ref", "type": "INT", "description": "FK to v_policies.policy_id (SourceRef)"},
                {"name": "policy_number", "type": "VARCHAR", "description": "Policy number"},
                {"name": "commission_type", "type": "VARCHAR", "description": "Commission type"},
                {"name": "carrier_code", "type": "VARCHAR", "description": "Carrier code"},
                {"name": "charged_amount", "type": "DECIMAL", "description": "Charged amount"},
            ],
        },
        {
            "table_name": "v_claims",
            "table_description": "Claims details view.",
            "columns": [
                {"name": "claim_id", "type": "INT", "description": "Unique claim ID"},
                {"name": "claim_number", "type": "VARCHAR", "description": "Claim number"},
                {"name": "status", "type": "VARCHAR", "description": "Claim status"},
                {"name": "total_incurred", "type": "DECIMAL", "description": "Total incurred amount"},
                {"name": "loss_date", "type": "VARCHAR", "description": "Date of loss"},
                {"name": "reported_date", "type": "VARCHAR", "description": "Date reported"},
                {"name": "description", "type": "VARCHAR", "description": "Claim description"},
                {"name": "adjuster", "type": "VARCHAR", "description": "Adjuster name"},
                {"name": "policy_ref", "type": "VARCHAR", "description": "FK to v_policies.policy_id (CAST required)"},
            ],
        },
        {
            "table_name": "v_payments",
            "table_description": "Payment details view.",
            "columns": [
                {"name": "payment_id", "type": "INT", "description": "Unique payment ID"},
                {"name": "policy_ref", "type": "VARCHAR", "description": "FK to v_policies.policy_id (CAST required)"},
                {"name": "amount", "type": "DECIMAL", "description": "Payment amount"},
                {"name": "payment_date", "type": "VARCHAR", "description": "Payment date"},
                {"name": "payment_type", "type": "VARCHAR", "description": "Payment type"},
            ],
        },
        {
            "table_name": "v_notes",
            "table_description": "Notes view.",
            "columns": [
                {"name": "note_id", "type": "INT", "description": "Unique note ID"},
                {"name": "policy_ref", "type": "VARCHAR", "description": "FK to v_policies.policy_id (CAST required)"},
                {"name": "claim_ref", "type": "VARCHAR", "description": "FK to v_claims.claim_id (CAST required)"},
                {"name": "author", "type": "VARCHAR", "description": "Author"},
                {"name": "note_date", "type": "VARCHAR", "description": "Note date"},
                {"name": "note_text", "type": "VARCHAR", "description": "Note content"},
            ],
        },
    ],
    "relationships": [
        {
            "description": "Customer to Policy",
            "join": "v_policies.customer_ref = v_customers.customer_id (use CAST(v_policies.customer_ref AS UNSIGNED) = v_customers.customer_id)",
            "example": "SELECT c.customer_name, p.policy_number, p.status FROM v_policies p JOIN v_customers c ON c.customer_id = CAST(p.customer_ref AS UNSIGNED)",
        },
        {
            "description": "Customer to Provider",
            "join": "v_customers.provider_ref = v_providers.provider_id (use CAST(v_customers.provider_ref AS UNSIGNED) = v_providers.provider_id)",
            "example": "SELECT c.customer_name, pr.provider_name FROM v_customers c JOIN v_providers pr ON pr.provider_id = CAST(c.provider_ref AS UNSIGNED)",
        },
        {
            "description": "Policy to Provider",
            "join": "v_policies.provider_ref = v_providers.provider_id",
            "example": "SELECT p.policy_number, pr.provider_name FROM v_policies p JOIN v_providers pr ON pr.provider_id = CAST(p.provider_ref AS UNSIGNED)",
        },
        {
            "description": "Commission to Provider",
            "join": "v_commissions.provider_ref = v_providers.provider_id",
        },
        {
            "description": "Claim to Policy",
            "join": "v_claims.policy_ref = v_policies.policy_id (use CAST(v_claims.policy_ref AS UNSIGNED) = v_policies.policy_id)",
        },
        {
            "description": "Payment to Policy",
            "join": "v_payments.policy_ref = v_policies.policy_id (use CAST(v_payments.policy_ref AS UNSIGNED) = v_policies.policy_id)",
        },
        {
            "description": "Note to Policy",
            "join": "v_notes.policy_ref = v_policies.policy_id (use CAST(v_notes.policy_ref AS UNSIGNED) = v_policies.policy_id)",
        },
        {
            "description": "Note to Claim",
            "join": "v_notes.claim_ref = v_claims.claim_id (use CAST(v_notes.claim_ref AS UNSIGNED) = v_claims.claim_id)",
        },
    ],
}

SEMANTIC_MODEL_STR = json.dumps(semantic_model, indent=2)
